title: 数理ノート  # ← 表示されるサイトタイトル
email: your-email@example.com
description: >-
  数式が書けて装飾的なJekyllサイトです。
baseurl: "" # ← 空にする
url: "https://u5491.github.io"  # ← GitHubユーザー名に合わせます

twitter_username: jekyllrb
github_username: u5491

# remote_theme: "mmistakes/minimal-mistakes" -> theme: minima
# theme: minima
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true

# 「pages」に適用した方が md ファイルに反映されやすいです
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      toc: true
      toc_sticky: true
      toc_label: "目次"

collections:
  pages:
    output: true
    permalink: /:name/